spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dbcp:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
  #Redis
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

logging:
  level:
    org:
      springframework: DEBUG

security:
  jwt:
    access-token-expiration-minutes : 259200000
    refresh-token-expiration-minutes: 432000000
    secret-key: ${SECRET_KEY}

    #refreshToken time : 1000L * 60 * 60 * 24 * 5 //432000000
    #accessToken time : 1000L * 60 * 60 * 24 * 3 //259200000

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: ${SPRING_DOCS_PATH}
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  adminMail: ${MAIL_ADMIN}
  password: ${MAIL_PASSWORD}
  smtpAuth: true
  smtpSslEnable: true
  smtpStarttlsEnable: false
  smtpSslTrust: ${MAIL_SMTP_SSL_TRUST}

sms:
  apiKey: ${SMS_APIKEY}
  secretKey: ${SMS_SECRET_KEY}
  adminPhone: ${SMS_ADMIN}

