spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dbcp:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
  #Redis
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

logging:
  level:
    org:
      springframework: DEBUG

security:
  jwt:
    access-token-expiration-minutes : 259200000
    refresh-token-expiration-minutes: 432000000
    secret-key: ${SECRET_KEY}

    #refreshToken time : 1000L * 60 * 60 * 24 * 5 //432000000
    #accessToken time : 1000L * 60 * 60 * 24 * 3 //259200000
